// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using DeliveryApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliveryApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("merchant_public_seq", "shared");

            modelBuilder.HasSequence("order_public_seq", "shared");

            modelBuilder.HasSequence("user_public_seq", "shared");

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Customers.Address", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("AddressType")
                        .HasColumnType("tinyint");

                    b.Property<string>("BuildingName")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DoorInfo")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Floor")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.HasIndex("UserID", "IsDefault")
                        .IsUnique()
                        .HasFilter("[IsDefault] = 1");

                    b.ToTable("Address", "customers");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Customers.Orders.Order", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CancelledById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("CancelledByType")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("DeliveryFeeSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("DistanceKmSnapshot")
                        .HasColumnType("float");

                    b.Property<string>("IssueNote")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("IssueReason")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("ItemsTotalSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("MerchantID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("OrderType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PaymentStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("PublicID")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("RequiredDriversCount")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TipAmountSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmountSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("CancelledById");

                    b.HasIndex("PublicID")
                        .IsUnique()
                        .HasFilter("[PublicID] IS NOT NULL");

                    b.HasIndex("CustomerID", "CreatedAt");

                    b.HasIndex("MerchantID", "Status")
                        .HasFilter("[MerchantID] IS NOT NULL");

                    b.HasIndex("Status", "CreatedAt")
                        .HasFilter("[Status] = 2");

                    b.ToTable("Order", "customers");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Customers.Orders.OrderAssignment", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DriverID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RemoveReason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.HasIndex("DriverID", "Status");

                    b.HasIndex("OrderID", "DriverID")
                        .IsUnique();

                    b.HasIndex("OrderID", "Status");

                    b.ToTable("OrderAssignment", "customers");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Customers.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerNote")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("LineTotalSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VariantNameSnapshot")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItem", "customers");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Drivers.Driver", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveOrdersCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ApprovedByAdminID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DisabledByAdminID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLocationAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RatingsCount")
                        .HasColumnType("int");

                    b.Property<Guid>("VehicleTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ApprovedByAdminID");

                    b.HasIndex("DisabledByAdminID");

                    b.HasIndex("VehicleTypeID", "IsEnabled", "IsAvailable", "LastSeenAt");

                    b.ToTable("Driver", "drivers");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Drivers.DriverLocation", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriverID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("DriverID", "RecordedAt");

                    b.ToTable("DriverLocation", "drivers");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Drivers.DriverRequest", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DrivingLicenseNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DrivingLicensePhotoUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NationalIdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NationalIdPhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PersonalPhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ReviewedByAdminID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VehiclePlateNumber")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("VehicleTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("DrivingLicenseNumber")
                        .IsUnique()
                        .HasFilter("[DrivingLicenseNumber] IS NOT NULL AND [Status] IN (1, 2)");

                    b.HasIndex("NationalIdNumber")
                        .IsUnique()
                        .HasFilter("[Status] IN (1, 2)");

                    b.HasIndex("ReviewedByAdminID");

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasFilter("[Status] = 1");

                    b.HasIndex("VehiclePlateNumber")
                        .IsUnique()
                        .HasFilter("[VehiclePlateNumber] IS NOT NULL AND [Status] IN (1, 2)");

                    b.HasIndex("VehicleTypeID");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("DriverRequest", "drivers");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Drivers.VehicleType", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommissionPercent")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("MaxDistanceKm")
                        .HasColumnType("float");

                    b.Property<double>("MaxMergeExtraKm")
                        .HasColumnType("float");

                    b.Property<int>("MaxOrdersToBatch")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresLicenseAndPlate")
                        .HasColumnType("bit");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("VehicleName")
                        .IsUnique();

                    b.ToTable("VehicleType", "drivers");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Engagements.Notification", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("RelatedEntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("RelatedEntityType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("RelatedEntityType", "RelatedEntityID");

                    b.HasIndex("UserID", "IsRead", "CreatedAt");

                    b.ToTable("Notification", "engagement");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Engagements.Rating", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RatedEntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RaterUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Stars")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TargetType")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.HasIndex("RaterUserID");

                    b.HasIndex("OrderID", "RaterUserID", "TargetType")
                        .IsUnique();

                    b.HasIndex("TargetType", "RatedEntityID", "CreatedAt");

                    b.ToTable("Rating", "engagement");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("AccountStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("CustomerAverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("CustomerRatingsCount")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsProfileComplete")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Phone")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PublicID")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("RoleMask")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SuspendedUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("[Phone] IS NOT NULL");

                    b.HasIndex("PublicID")
                        .IsUnique()
                        .HasFilter("[PublicID] IS NOT NULL");

                    b.ToTable("User", "identity");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Identity.UserIdentity", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<byte>("Provider")
                        .HasColumnType("tinyint");

                    b.Property<string>("ProviderUserId")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasFilter("[ProviderUserId] IS NOT NULL");

                    b.HasIndex("UserID", "Provider")
                        .IsUnique();

                    b.ToTable("UserIdentity", "identity");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Identity.UserSession", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ClientType")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeviceID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("refreshTokenHash")
                        .IsRequired()
                        .HasColumnType("varbinary(32)")
                        .HasColumnName("RefreshTokenHash");

                    b.HasKey("ID");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("refreshTokenHash")
                        .IsUnique();

                    b.HasIndex("UserID", "ClientType")
                        .IsUnique();

                    b.ToTable("UserSession", "identity");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Merchants.Catalog.MerchantCategory", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MerchantID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MerchantID");

                    b.HasIndex("MerchantID", "CategoryName")
                        .IsUnique();

                    b.HasIndex("MerchantID", "SortOrder")
                        .IsUnique();

                    b.HasIndex("MerchantID", "IsActive", "SortOrder")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("MerchantCategory", "merchants");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Merchants.Catalog.MerchantSystemCategory", b =>
                {
                    b.Property<Guid>("MerchantID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SystemCategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MerchantID", "SystemCategoryID");

                    b.HasIndex("SystemCategoryID");

                    b.ToTable("MerchantSystemCategory", "merchants");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Merchants.Catalog.Product", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MerchantCategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MerchantCategoryID");

                    b.HasIndex("MerchantCategoryID", "ProductName")
                        .IsUnique();

                    b.HasIndex("MerchantCategoryID", "SortOrder")
                        .IsUnique();

                    b.HasIndex("MerchantCategoryID", "IsActive", "SortOrder")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Product", "merchants");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Merchants.Catalog.SystemCategory", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte>("MerchantType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MerchantType", "CategoryName")
                        .IsUnique();

                    b.HasIndex("MerchantType", "Slug")
                        .IsUnique();

                    b.HasIndex("MerchantType", "IsActive", "SortOrder")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("SystemCategory", "merchants");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Merchants.Catalog.Variant", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ProductID", "SortOrder")
                        .IsUnique();

                    b.HasIndex("ProductID", "VariantName")
                        .IsUnique();

                    b.HasIndex("ProductID", "IsActive", "SortOrder")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Variant", "merchants");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Merchants.Merchant", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeSpan>("DefaultPreparationTime")
                        .HasColumnType("time");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte>("MerchantType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PublicID")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("RatingsCount")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.HasKey("ID");

                    b.HasIndex("PublicID")
                        .IsUnique()
                        .HasFilter("[PublicID] IS NOT NULL");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("MerchantType", "IsActive")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Merchant", "merchants");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Merchants.MerchantUser", b =>
                {
                    b.Property<Guid>("MerchantID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.HasKey("MerchantID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("MerchantUser", "merchants");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Merchants.MerchantWorkingHour", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time");

                    b.Property<byte>("Day")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpenAllDay")
                        .HasColumnType("bit");

                    b.Property<Guid>("MerchantID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time");

                    b.HasKey("ID");

                    b.HasIndex("MerchantID");

                    b.HasIndex("MerchantID", "Day")
                        .IsUnique();

                    b.ToTable("MerchantWorkingHour", "merchants");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Moderation.AccountWarning", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByAdminID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DecidedByAdminID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Decision")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte>("Reason")
                        .HasColumnType("tinyint");

                    b.Property<string>("ReasonDetails")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("RelatedOrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Severity")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.HasIndex("CreatedByAdminID");

                    b.HasIndex("DecidedByAdminID");

                    b.HasIndex("Decision");

                    b.HasIndex("RelatedOrderID")
                        .HasFilter("[RelatedOrderID] IS NOT NULL");

                    b.HasIndex("EntityType", "EntityID", "CreatedAt");

                    b.HasIndex("EntityType", "EntityID", "RelatedOrderID", "Reason")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("AccountWarning", "moderation");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Moderation.Complaint", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminResponse")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Reason")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ReviewedByAdminID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("TargetID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("TargetType")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ReviewedByAdminID");

                    b.HasIndex("Status");

                    b.HasIndex("TargetType", "TargetID", "CreatedAt");

                    b.HasIndex("CreatedByUserID", "OrderID", "TargetType", "TargetID", "Reason")
                        .IsUnique()
                        .HasFilter("[Status] = 1");

                    b.ToTable("Complaint", "moderation");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Moderation.Zones.Zone", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsServiceable")
                        .HasColumnType("bit");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.HasIndex("ZoneName")
                        .IsUnique();

                    b.HasIndex("IsActive", "IsServiceable")
                        .HasFilter("[IsActive] = 1 AND [IsServiceable] = 1");

                    b.ToTable("Zone", "moderation");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Moderation.Zones.ZonePolygon", b =>
                {
                    b.Property<Guid>("ZoneID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ZoneID", "SortOrder");

                    b.ToTable("ZonePolygon", "moderation");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Customers.Address", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DeliveryApp.Domain.ValueObjects.GeoPoint", "Location", b1 =>
                        {
                            b1.Property<Guid>("AddressID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("AddressID");

                            b1.ToTable("Address", "customers");

                            b1.WithOwner()
                                .HasForeignKey("AddressID");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Customers.Orders.Order", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CancelledById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryApp.Domain.Entities.Merchants.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("DeliveryApp.Domain.ValueObjects.GeoPoint", "DropoffLocation", b1 =>
                        {
                            b1.Property<Guid>("OrderID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("DropoffLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("DropoffLongitude");

                            b1.HasKey("OrderID");

                            b1.ToTable("Order", "customers");

                            b1.WithOwner()
                                .HasForeignKey("OrderID");
                        });

                    b.OwnsOne("DeliveryApp.Domain.ValueObjects.GeoPoint", "PickupLocation", b1 =>
                        {
                            b1.Property<Guid>("OrderID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("PickupLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("PickupLongitude");

                            b1.HasKey("OrderID");

                            b1.ToTable("Order", "customers");

                            b1.WithOwner()
                                .HasForeignKey("OrderID");
                        });

                    b.Navigation("DropoffLocation")
                        .IsRequired();

                    b.Navigation("PickupLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Customers.Orders.OrderAssignment", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryApp.Domain.Entities.Customers.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Customers.Orders.OrderItem", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Customers.Orders.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Drivers.Driver", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByAdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("DisabledByAdminID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("DeliveryApp.Domain.Entities.Drivers.Driver", "ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryApp.Domain.Entities.Drivers.VehicleType", null)
                        .WithMany()
                        .HasForeignKey("VehicleTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DeliveryApp.Domain.ValueObjects.GeoPoint", "CurrentLocation", b1 =>
                        {
                            b1.Property<Guid>("DriverID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("CurrentLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("CurrentLongitude");

                            b1.HasKey("DriverID");

                            b1.ToTable("Driver", "drivers");

                            b1.WithOwner()
                                .HasForeignKey("DriverID");
                        });

                    b.Navigation("CurrentLocation");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Drivers.DriverLocation", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Drivers.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DeliveryApp.Domain.ValueObjects.GeoPoint", "Location", b1 =>
                        {
                            b1.Property<Guid>("DriverLocationID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("DriverLocationID");

                            b1.ToTable("DriverLocation", "drivers");

                            b1.WithOwner()
                                .HasForeignKey("DriverLocationID");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Drivers.DriverRequest", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryApp.Domain.Entities.Drivers.VehicleType", null)
                        .WithMany()
                        .HasForeignKey("VehicleTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Engagements.Notification", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Engagements.Rating", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Customers.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("RaterUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Identity.UserIdentity", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Identity.UserSession", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Merchants.Catalog.MerchantCategory", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Merchants.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Merchants.Catalog.MerchantSystemCategory", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Merchants.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryApp.Domain.Entities.Merchants.Catalog.SystemCategory", null)
                        .WithMany()
                        .HasForeignKey("SystemCategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Merchants.Catalog.Product", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Merchants.Catalog.MerchantCategory", null)
                        .WithMany()
                        .HasForeignKey("MerchantCategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Merchants.Catalog.Variant", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Merchants.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Merchants.Merchant", b =>
                {
                    b.OwnsOne("DeliveryApp.Domain.ValueObjects.GeoPoint", "Location", b1 =>
                        {
                            b1.Property<Guid>("MerchantID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("MerchantID");

                            b1.ToTable("Merchant", "merchants");

                            b1.WithOwner()
                                .HasForeignKey("MerchantID");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Merchants.MerchantUser", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Merchants.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Merchants.MerchantWorkingHour", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Merchants.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Moderation.AccountWarning", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("DecidedByAdminID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeliveryApp.Domain.Entities.Customers.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("RelatedOrderID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Moderation.Complaint", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryApp.Domain.Entities.Customers.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryApp.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Moderation.Zones.ZonePolygon", b =>
                {
                    b.HasOne("DeliveryApp.Domain.Entities.Moderation.Zones.Zone", null)
                        .WithMany("Polygons")
                        .HasForeignKey("ZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DeliveryApp.Domain.ValueObjects.GeoPoint", "Location", b1 =>
                        {
                            b1.Property<Guid>("ZonePolygonZoneID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("ZonePolygonSortOrder")
                                .HasColumnType("int");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("ZonePolygonZoneID", "ZonePolygonSortOrder");

                            b1.ToTable("ZonePolygon", "moderation");

                            b1.WithOwner()
                                .HasForeignKey("ZonePolygonZoneID", "ZonePolygonSortOrder");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Customers.Orders.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DeliveryApp.Domain.Entities.Moderation.Zones.Zone", b =>
                {
                    b.Navigation("Polygons");
                });
#pragma warning restore 612, 618
        }
    }
}